<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<h1>Demo: Direct Access</h1>
<p>Use as user</p>
<ul>
    <li><a href="login.php?do=DA&u=1">Travis (ID: 1)</a></li>
    <li><a href="login.php?do=DA&u=2">Msquashic (ID: 2)</a></li>
    <li><a href="login.php?do=DA&u=3">Gerry (ID: 3)</a></li>
    
</ul>